### ISSUE TITLE
Remix // Adjust the color code in the component with a background picture to make text easy to read

### ISSUE THREAD

**Issue by NoeliaEle** [HerrBertling/virtualsupporttalks#102]
🔍 

![Screenshot 2022-05-11 at 18 22 08](https://user-images.githubusercontent.com/88032788/167899281-3ea82d1d-a19e-4a92-b0dd-33786a34ecb6.png)

**Comment by HerrBertling** [comment]
Fixed in https://github.com/HerrBertling/virtualsupporttalks/pull/78/commits/5ca8edda8df444a9b2610530199ee7e992027230
