### ISSUE TITLE
Little Things to fix on new website

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#107]
Hello,

Just found some little things to fix on the new website (list continuing):

- [x] Contentful Logo in website footer => https://github.com/HerrBertling/virtualsupporttalks/commit/6106dc4d7245c78cae8a6859ffe9a67c130e35f6
- [ ] #109
- [x] using the filter option do not narrows the offer of listeners down but increases the number of listeners (shouldnt the number of listeners decrease the more option I choose?)
- [x] Check whether we have content blocks at all in partner/media page. It checks for all content parts except the content blocks. If they are removed, the page crashes.
- [ ] #110

🙏🏻🦄🥳 Love the new features!! Thanks for your hard work! ❤️

**Comment by HerrSchleinig** [comment]
I think we need to press a few more buttons here in the Analytics backend to get this working again.... I just saw that there is no data stream for iOs and Android: https://analytics.google.com/analytics/web/#/a164320013p265825665/admin/streams/table. I think they really changed a lot with the new system.... Why? 🤔😟

<img width="1273" alt="Bildschirmfoto 2022-05-24 um 14 07 35" src="https://user-images.githubusercontent.com/80904689/170031042-b4e63df7-d2e7-41cb-a108-88b3b47d4678.png">

**Comment by NoeliaEle** [comment]
Hey team, I just saw this ticket. In regards to:

> using the filter option does not narrow the offer of listeners down but increases the number of listeners (shouldn't the number of listeners decrease the more option I choose?)

I'm not sure if that's the usage we want to give to the language filter in our case. If I speak EN & ES fluently, I wouldn't mind getting the session in one **OR** the other language, I wouldn't necessarily need someone that speaks **both**. 
If on another situation, I feel only a Spanish-speaking person could fully understand me, then I would only choose ES as a language filter.
I think changing the filter to narrow the search benefits people that speak multiple languages but it might leave behind the one that only speaks Spanish and that could really help me for example, let me know your thoughts!

@HerrBertling @HerrSchleinig

**Comment by HerrSchleinig** [comment]
Hey team,

Thanks, Noelia, for your thoughts! Appreciated! And I think I get it what you say. May thoughts pointed only on the issues user can select, not the languages. I am totally with you that someone who feels speaking better Spanish then choose a listener speaking better Spanish then German AND SPANISCH.

I was just thinking regarding selecting the issues: The more I choose because some issues come together I would feel better when I see only listeners combining listen to both or more issues (depending on what I choose so far).

Do you see what I mean? :-) Hope that I can express my thoughts without misunderstandings :-)

Best

Flo

**Comment by NoeliaEle** [comment]
Hey Flo,

Absolutely, thanks for your nice response! I don't know why in my head I only thought about the language filters because we were talking about them recently. Apologies for that 🙏 

I see what you mean and I agree that it makes sense for a small selection of topics that are related. The risk would be that we can't provide any results to users who need to deal with multiple varied topics, but they can then do different searches. I think we would need a different UX if we want to cover that, we could check it if it becomes an issue or a blocker for our users :) Filters are always such a tricky and entertained feature to build 😄 !

**Comment by HerrSchleinig** [comment]
Hi Noelia,

Thanks for your nice mail! I get you completely and I agree totally with the idea to see how we can deal with situations in which users have multiple varied topics and go off the offer for their combination. 

My thought would be a kind of information presenting saying that they would need to decrease the combination to get a hit for listeners, forecasting that we then would have at least one listener fitting their needs. And maybe additionally the note that we develop the offer shown through the filter and we would love to hear their comment by email? So to step into communication with them without leaving them alone when the search wasnt successful?

And do think you would be able to see when someone hit to many issues in the filter without a result coming up? :-) 

And I can totally imagine building filters is not an easy and simple thing!!! 🙏🏻❤️ I love you guys for this!

Flo

**Comment by HerrBertling** [comment]
I'll close here since the two open points already have their individual issues :)
