### ISSUE TITLE
Localize images

### ISSUE THREAD

**Issue by HerrBertling** [HerrBertling/virtualsupporttalks#110]
May it be possible to add images in different languages to different content pieces like to Join Our Team page: https://www.virtualsupporttalks.de/de/mitmachen (here is the German image included but also on the English page)

**Comment by NoeliaEle** [comment]
I think this is already done, @HerrSchleinig could you try adding some images on different languages on the same language item? (Once back from vacation 🌴 😄 )
Then we can close this issue
<img width="1013" alt="Screenshot 2023-08-11 at 12 28 45" src="https://github.com/HerrBertling/virtualsupporttalks/assets/88032788/03dc914e-3d9f-44f1-8a45-c71d919b2f57">

**Comment by HerrSchleinig** [comment]
Hi Noelia,

Thank you so much for taking of this issue! It works!

Best 

Flo
