### ISSUE TITLE
404 NOT FOUND

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#118]
Hello,

I got the notice today that if you click in LESEZEIT on a specific tag like "mental health" you get a result of all articles tagged under the tag but you cannot open the article. It shows 404 NOT FOUND then. As you can see on the screen shot 😊
<img width="657" alt="Bildschirmfoto 2022-08-24 um 20 42 22" src="https://user-images.githubusercontent.com/80904689/186497875-85c4ce30-c19f-42bc-a4e2-015fcc3c40f9.png">

Would you maybe have the chance to have a look into this? 🙏🏻💚

Thank you! ❤️

<img width="926" alt="Bildschirmfoto 2022-08-24 um 20 42 14" src="https://user-images.githubusercontent.com/80904689/186497861-9aa935b7-a33b-41c4-911e-528b78609386.png">

**Comment by HerrBertling** [comment]
Fixed this :) https://github.com/HerrBertling/virtualsupporttalks/pull/120

**Comment by HerrSchleinig** [comment]
🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳🥳

**Comment by HerrSchleinig** [comment]
Muss Dich leider enttäuschen, es funktioniert noch nicht, sehe Screenshot 😔😔
Oder hab ich was falsch verstanden?

LG; Flo

**Comment by HerrBertling** [comment]
Gleich aber! :)
