### ISSUE TITLE
Filter option Male, Female, Diverse (?)

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#119]
Hello Team,

We got the feedback maybe to have the filter option also for male and female listeners to choose from. I was thinking of two ways to pay to the feednack:

1. I just open new tags of male and female and select the listeners to the regular tags. Or...
2.  Would you think it might be possible to add a filter section for male and female?

What would you think? I guess, solution no 1 is most easiest and quickes way, right?

Best wishes

Flo

**Comment by NoeliaEle** [comment]
Sounds good! 

We might want to add female - male - diverse. 
If there would be a way to communicate with our coaches that we are making web improvements and adding a gender filter, and if any of them prefer to be referred to as 'diverse gender' (not male or female), they could just send us a quick email. Maybe it's over-engineered, but I think it might not be positive if we assume the identity of someone without giving them the chance to define it themselves, more considering our context. But of course, if we don't have the resources, we go for what we think and we can always change it afterwards. 

We need to check the 'how' - could be that we add a separate field. We will come back to you when we need support on filling contenful! Thanks!

**Comment by NoeliaEle** [comment]
Sounds good!

**Comment by HerrBertling** [comment]
Done in #136
