### ISSUE TITLE
REDEZEIT video clip  on iPad browser

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#121]
Hello team,

Last week I had a chance by colleague using REDEZEIT on an iPad which I never enjoyed so far. I saw the video content peace and made some screenshots to show you how I noticed it on the lading page I first had implemented it.

One shot is crossways holding and the other is upright holding. Would you think you may have a look into it?

Thank you so much! ❤️❤️

![IMG_94EF06D6F407-1](https://user-images.githubusercontent.com/80904689/189728916-6eed22e5-b910-49b8-bd28-a00b109b45be.jpeg)
![IMG_9E8E25F768D1-1](https://user-images.githubusercontent.com/80904689/189728925-b45bf998-b101-4383-b056-dd36cbe0380b.jpeg)

**Comment by Francine-Pepe** [comment]
Hi Florian! At the moment seems fine. 
![Captura de Tela (207)](https://user-images.githubusercontent.com/88684422/189980691-ca9bffe3-c520-4827-bd06-64765419fab6.png)

**Comment by NoeliaEle** [comment]
Thanks @HerrSchleinig , do you mean that the text and video appear in the horizontal formal, side by side, and on the vertical format, video below the text?


I'm using it on an iPad and I'm seeing some other issues with the display, will take a look at it!

![IMG_0006](https://user-images.githubusercontent.com/88032788/190349432-5195750b-9020-4cd2-b71c-62644f9eac6f.PNG)

![IMG_479B341570B1-1](https://user-images.githubusercontent.com/88032788/190349436-7971384a-ee82-4b56-a3e0-9a5ce57f07e5.jpeg)

**Comment by HerrSchleinig** [comment]
Hi Noelia,

Thanks for having a look into this 🙏🏻💚 

It was like I couldnt once see the video with half of the belonging text above and once I could it one see on a very narrow line. 🫣🙂

Flo

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________

**Comment by NoeliaEle** [comment]
Hi @HerrSchleinig ! we merged this end of last week - It should be working fine now! I tested it on my own iPad and it works. If you get the chance to check it again, please do so and send us screenshots again if there is anything wrong. Thanks!
