### ISSUE TITLE
Englische Corporate Pages

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#16]
Huhu, weißt Du, was ich einstellen muss, um die englische Seite von der hier zu sehen? [https://www.virtualsupporttalks.de/realdigital](https://www.virtualsupporttalks.de/realdigital)?

Englischer Text ist drin in den Content Modulen.

Danke 🥳

**Comment by HerrBertling** [comment]
Ich wusste, dass du dir einen Account erstellst! Der erste Schritt zum `l33t h4XX0r`!!! :joy:

**Comment by HerrSchleinig** [comment]
🤣🤣🤣🤣✌🏻✌🏻✌🏻

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________

**Comment by HerrSchleinig** [comment]
Ich pass mich Deiner Arbeitsweise an. Macht es einfach für Dich ❤️🙏🏻

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________
