### ISSUE TITLE
Schmalere Logo-Leiste auf mobil

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#25]
![WhatsApp Image 2021-04-09 at 20 03 11](https://user-images.githubusercontent.com/80904689/114296275-ac412380-9aaa-11eb-8e5d-0a62d7f4d407.jpeg)

Geht es, die Logo-Leiste auf mobil etwas schmaler zu machen, ohne die Ansicht auf Desktop zu berühren?

**Comment by HerrBertling** [comment]
In https://github.com/HerrBertling/virtualsupporttalks/pull/26 gemacht 😊
