### ISSUE TITLE
Neuen Google Analytics Tag

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#28]
Neuer Tag für das neue Google Analytics: 

G-3203CF2NDT

**Comment by HerrBertling** [comment]
Das kann das Plugin, das wir nutzen, leider noch nicht 😑

**Comment by HerrSchleinig** [comment]
Nicht schlimm ☺️🥸✌🏻

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________

**Comment by HerrSchleinig** [comment]
Huhu, guten Morgen,

es gibt ein neues Analytics. Meinst Du, Du kannst mal schauen, ob der folgende Tag funktioniert mit unserem Plugin? Danke! ❤️🙏🏻


<script async src="https://www.googletagmanager.com/gtag/js?id=UA-164320013-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-164320013-1');
</script>

**Comment by HerrBertling** [comment]
This will go live with the Remix setup, see here: https://github.com/HerrBertling/virtualsupporttalks/pull/78/commits/40a3d156931406fad499e1f8aa06e24faffc564c#diff-e9859be541540c81c3f3716e2869ac2b1e282a07e960cf11a1ff107f65200760
