### ISSUE TITLE
Fond hinter Linkleiste

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#30]
![Bildschirmfoto 2021-05-04 um 21 10 35](https://user-images.githubusercontent.com/80904689/117056988-37fe4680-ad1d-11eb-8a0d-0e4857a5bad2.png)

Huhu können wir hier eventuell einen Fond oder sowas machen, damit die Links sich quasi vom Websiteinhalt abheben und nicht vermixen? :-) ❤️

Vielen lieben Dank!

**Comment by HerrSchleinig** [comment]
Irgendwie ist der jetzt da. Keine Ahnung, ob es an meinem Browser lag?

**Comment by HerrBertling** [comment]
Schaue noch mal nach. Kann sein, dass der Header nicht korrekt weiß hinterlegt wird, wenn man auf der Seite schon gescrollt hat und sie dann neu lädt.
