### ISSUE TITLE
Eine Seite nur für Kachel-Grafiken

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#49]
Helloo, sag, wäre es möglich, eine Seite aufzusetzen, auf der nur Kachelgrafiken erscheinen? Wir fahren aktuell eine kleine Change-Kampagne - weg von dem Corona-Ding, hin zum übergeordneten Thema Seelische Gesundheit. Ich würde gerne eine Art Kampagnenseite aufsetzen, wo wir alle Ambassadors, die uns unterstützen mit ihren Statements integrieren.

Weißt Du, was ich meine? Ein paar Bsp im Anhang :-)

Danke Dir sehr!

Grüße

Flo

![FrankBehrendt_Kachel Kopie](https://user-images.githubusercontent.com/80904689/137937314-e046cb66-21a8-4d08-ac23-d0ad8006aa9c.jpg)
![Kathrynsky_Kachel Kopie](https://user-images.githubusercontent.com/80904689/137937331-a7e7d8a8-3bad-4a95-9b16-a08f192ed0cc.jpg)
![StadtLandMama_Kachel Kopie](https://user-images.githubusercontent.com/80904689/137937351-cbb1b0fd-7139-4efc-a9d8-200c3ebcc479.jpg)

![MichaFritz_Kachel Kopie](https://user-images.githubusercontent.com/80904689/137937339-4b9d6d7e-08ba-4bb0-a49d-218eecca930a.jpg)
![SaraUrbainczyk_Kachel Kopie](https://user-images.githubusercontent.com/80904689/137937345-8aa5eb10-d79f-4520-963a-c4ddf275d6b8.jpg)

**Comment by HerrBertling** [comment]
Ja! Die könnten wir doch super als Inhaltsblock bauen – ein paar feste, gleich bleibende Elemente und dazu:

- Bild
- Zitat
- Name
- Titel/Job/…

Dann baue ich das per CSS zusammen und es sieht über alle Devices schick aus.

Oder sollen es einfach™ Bilder sein? Dann wäre der Text natürlich nicht (aus-)lesbar.
