### ISSUE TITLE
Partner-Slider

### ISSUE THREAD

**Issue by HerrBertling** [HerrBertling/virtualsupporttalks#5]
Gibt es vllt eine Art Slider für die Partner-Seite, in den ich Partner zu Wort kommen lassen kann?

**Comment by HerrSchleinig** [comment]
Hab das erst einmal so gelöst :-D https://www.virtualsupporttalks.de/netzwerk-partner-medien/

**Comment by HerrBertling** [comment]
:+1: Sieht doch gut aus und [man kann es problemlos lesen](https://shouldiuseacarousel.com/) 😄 😝
