### ISSUE TITLE
New language: Polish

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#51]
Hello, wir haben eine polnisch sprechende Zuhörerin. Magst Du einmal bitte die Sprache Polish einstellen?

Danke Dir ❤️

**Comment by HerrBertling** [comment]
Ich hab schon irgendwann mal „pol“ für polnisch hinterlegt, wenn das im CMS so steht, dann sollte das auch angezeigt werden 😊

**Comment by HerrSchleinig** [comment]
❤️❤️❤️🙏🏻🙏🏻🙏🏻
