### ISSUE TITLE
Hinterlegen einer Telefonnummer

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#57]
Hello,

wir wollen ab Januar den Zuhörer*Innen anbieten, ihre Telefonnummer mit zu hinterlegen für schnellere Kontaktaufnahme. Geht es, zusätzlich zur Website und Emailadresse auch noch ein Feld für die Telefonnummer ins CMS einzubauen?

Lieben Dank Dir! ❤️🙏🏻

**Comment by HerrBertling** [comment]
Wenn ihr welche hinzufügt, dann sieht man jetzt neben ner Weltkugel (Webseite) und nem Brief (E-Mail) auch einen Telefonhörer mit vernünftigem Anrufen-Link 😊

**Comment by HerrSchleinig** [comment]
🥳🥳🥳🥳 Yeah! Vielen Dank! Dann geht nächste Woche das Sonder-Update an die Community zwecks Dringlichkeit-Modus und Filter.

Wuhu!

Flo
