### ISSUE TITLE
Label für IN DRINGENDEN FÄLLEN

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#58]
Hello,

war ein guter Zwischendurchkaffee heute Morgen ❤️

Sag, besteht die Möglichkeit, im Profil optional ein Label oder einen farblichen Störer zu hinterlegen, wenn ein Zuhörer IN DRINGENDEN FÄLLEN erreichbar ist? Weißt Du, was ich meine?

LG, Flo

**Comment by HerrBertling** [comment]
So? 
![image](https://user-images.githubusercontent.com/1827373/148432741-769096d1-a342-4966-a7fa-c2777d81f318.png)

**Comment by HerrBertling** [comment]
Hab's in Contentful als Yes/No-Frage bei den Coaches hinzugefügt. Wenn man es auf "Yes" stellt, ist das Banner an der Coach-Card :)

**Comment by HerrSchleinig** [comment]
Pure Liebe!!! ❤️🥳 Mega!! Danke!!

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________
