### ISSUE TITLE
Zuhörer*innen gegen Coach

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#59]
Hello,

hattest Du noch ein schönes Wochenende? Freu mich aufs nächste Feuer! ❤️

Kleinigkeit, aber sag, kannst Du bitte einmal den Begriff Coaches in Zuhörer*innen ändern auf der ICH SUCHE REDEZEIT Seite direkt beim Aufklappen des Filters? 😊 Ich schaue gerade, überall den Begriff Coaches gegen Zuhörer*innen auszutauschen, da Coaches nur ein Qualitätsmerkmal ist, kein Angebot. Danke Dir sehr! 

<img width="1041" alt="Bildschirmfoto 2022-01-10 um 08 35 31" src="https://user-images.githubusercontent.com/80904689/148731566-c764c96a-4ee4-4f11-9fc1-1cd2a3996cd3.png">

**Comment by HerrBertling** [comment]
Steht da doch! Also… gleich 😝

**Comment by HerrSchleinig** [comment]
HAHAHA 😹 😂 😆 😝 Danke! ❤️

**Comment by HerrSchleinig** [comment]
Asche auf mein Haupt und so 😣😣😣😣😣

Die Mehrheit findet die gesamte Aussage zu "technisch"... Kannst Du es, wenn Du Zeit hast, bitte noch einmal ändern? <3 In:

In welcher Sprache möchtest du mit jemandem reden?

Was ist dein Thema?

**Comment by HerrBertling** [comment]
Done :)
