### ISSUE TITLE
Dokumentation der API 

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#71]
Hello nach Madeira,

habt Ihrs schön sonnig? Hamburg ist gerade um gefühlte 900 Kilometer nach Norden gerückt durch den Sturm. Ansonsten sind wir happy :-D

Wir wollen mit ama mind (https://ama-mind.com/) zusammenarbeiten. Und um unser Angebot auf deren Seite einzubinden, fragte der Programmierer nach einer Dokumentation unserer API. Hast Du da was, was Du mir geben könntest?

Ich habe so überhaupt gar kein Plan...

LG, Flo

**Comment by HerrBertling** [comment]
Soll mich mal anschreiben, dann mach ich nen Account + API Key für ihn.

**Comment by HerrSchleinig** [comment]
🥳🥳🥳🥳🥳🥳🥳🙏🏻🙏🏻🙏🏻❤️❤️❤️❤️❤️❤️ Mach ich! Sein Name ist Thorsten Loth. Ich gebe ihm Deine Kontaktdaten.

LG flo
