### ISSUE TITLE
Button, um Blogbeitrag als Email an Dritte zu schicken

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#72]
Huhu Maderianer 🥳✌🏻 Wie gehts Euch?

Können wir einen Email-senden-Button zu einem Blogbeitrag hinzufügen, so dass der Beitrag von einem Leser geteilt werden kann per Email? Die Kiste mit den Social-Plugins möchte ich nicht aufmachen. Aber per Email ginge sowas auch, oder?

Danke und viele Grüße,

Flo

**Comment by HerrBertling** [comment]
Einige Browser unterstützen den Share-Dialog, den man von iOS und Android kennt, aus der Box (Safari auf macOS + iOS, die anderen Browser auf Windows). Wenn das geht, wird ein Share-Icon angezeigt und triggert genau das Menü. Was da konkret drin steht, kann jeder User selbst auf seinem Gerät einstellen.

Wenn der entsprechende Browser das mit dem Sharing nicht kann (Chrome, Firefox auf nem Mac – frag nicht…), dann wird ein Mail-Icon angezeigt über das man halt ne Mail schickt. Das triggert dann das jeweilige Mail-Programm, das man eingestellt hat :)

Beispiel: https://deploy-preview-73--keen-liskov-77de74.netlify.app/blog/5-gruende-warum-eine-schwangerschaft-waehrend-corona-eine-chance-sein-kann/ – das bitte einmal auf'm iPhone mit Safari aufmachen und auf dem Rechner mit Chrome UND Safari, dann sieht man jeweils die Unterschiede beim Share-Dialog bzw. das Mail-Icon mit Chrome (oder jedem anderen Browser auf macOS, der *nicht* Safari ist, gnarf).

**Comment by HerrSchleinig** [comment]
Yeah!!!! Yes!!! Genau das ❤️❤️❤️ Danke!
