### ISSUE TITLE
Sharing Button Email in Blogbeitrag

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#75]
Huhu, Bussi nach Madeira,

wie gehts Euch? Genießt Ihr die Sonne?

Habe heute mal den Send-Button im Blog ausprobiert. Er ruft alles super auf, allerdings ist die Domain nicht ganz richtig, die er reinkopiert :-)

**_/blog/hilfe-fuer-helikopter-eltern-mit-diesen-7-tipps-kannst-du-dein-kind/

Helikopter-Eltern meinen es stets (zu) gut mit ihren Kindern. Wie ihr lernt, loszulassen und trotzdem Nähe zu euren Kindern zu leben, erklärt REDEZEITzuhörerin Astrid Meinberg._**

Lg; Flo

**Comment by HerrBertling** [comment]
Joa, so'ne komplette URL, das hätte was, ne? 😄 Ist jetzt gleich korrekt :)

**Comment by HerrSchleinig** [comment]
❤️❤️❤️ Danke!!

Markus, ich muss Dir mal echt sagen, Du hast so eine großartige Plattform aufgesetzt, das ist echt der Hammer! Ich bin immer wieder stolz erstaunt, was wir damit noch so alles machen… 🥳🤩

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________
