### ISSUE TITLE
Einbinden der Seite WER SIND WIR in Menü

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#76]
Huhuuuu,

wie gehts Euch? Brief ist auf dem Weg. Wenn ich noch was tun kann zwischendurch, gebt Bescheid!

Ich würde gerne die Seite WER SIND WIR https://www.virtualsupporttalks.de/wer-sind-wir ins Menü einbauen. Meinst Du, da ist noch Platz? Dafür können wir zum Beispiel die Seite NETZWERK, PARTNER+MEDIEN in PARTNER+MEDIEN oder nur in PARTNER umbenennen. Ich muss mir mal Gedanken machen, wie wir das mit der Berichterstattung künftig machen. Aber das ist jetzt noch nicht wichtig :-D

Und nach Einbindung von WER SIND WIR kannst Du den Part mit den Teammitgliedern auf der Landingpage bitte gerne einmal entfernen ❤️🙏🏻🥳✌🏻

Danke dir!

**Comment by HerrBertling** [comment]
Dit kannste nu selbst machen, wa? https://github.com/HerrBertling/virtualsupporttalks/commit/337205494249fb92f206df13024e1b1cbd6703a4 :D

**Comment by HerrBertling** [comment]
(Ich hab's gerade gemacht :) )

**Comment by HerrSchleinig** [comment]
Mega, danke! ❤️🤖 Magst Du dann einmal bitte auf der Startseite unten den Abschnitt mit den Teambildern rausnehmen? 😊🤘🏻

Danke!! 

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________
