### ISSUE TITLE
Umfrage über Popup Fenster auf der Startseite?

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#77]
Hello,

sag, gibt es die Möglichkeit, eine Popup-Fenster-Funktion zu installieren, um Umfragen und Botschaften dort auszusteuern?

LG, Flo

**Comment by HerrBertling** [comment]
Die Möglichkeit gäbe es schon, nur… will man das wirklich? Es gibt wenig nervigeres und ich würde dann auf jeden Fall tracken wollen, wie viele Menschen das Ding genervt wegklicken und die Seite verlassen 😛 

Die kann man doch auch als Inhaltsblock prominent als erstes oder zweites mit Absprung dorthin auf der Seite platzieren, oder?

**Comment by HerrSchleinig** [comment]
Ja, Du hast recht :-) Stimmt! Ich suche nach weiteren Möglichkeiten, die Besucher*innen ein Feedback zu entlocken, wenn sie da waren. Da muss ich mir noch mal eine bessere Strategie überlegen 😆❤️ Danke für Deinen Rat und Hinweis!
