### ISSUE TITLE
Kontaktformular für Feedback

### ISSUE THREAD

**Issue by HerrBertling** [HerrBertling/virtualsupporttalks#8]
Gibt es die Möglichkeit ein Kontaktfeld für anonymes Feedback aufzusetzen? Es wäre ein guter Touch Point für abgeschlossene Gespräche und für Feedback.

**Comment by HerrSchleinig** [comment]
Meine Gedanken für das Abfrageformular. Richtet sich an Nutzer unseres Angebots. Würde es ganz einfach und übersichtlich halten:

Herausforderung: Das Formular soll per Klick für Nutzer*in oder Zuhörer*in sein.

Nicht optionale Abfrageelemente:

- Wie hat Dir das Gespräch gefallen? 1-10
- Wie zufrieden warst Du der Terminfindung? 1-10
- Wie zufrieden warst Du mit Deiner*Deinem Zuhörer*in?
- Würdest Du REDEZEIT weiterempfehlen? Ja/nein

Optionale Abfrageelemente:

- Name des*der Zuhörer*in
- Freitext für persönliche Erfahrungen oder persönliche Botschaft (Hier kannst Du uns Deine persönliche Nachricht zukommen lassen:)

Dazu noch einen Intro-Text und auch noch mal unsere Kontaktdaten in Reinform (falls jemand dem Formular nicht traut). Und ein schönes Bild :-)

**Comment by HerrBertling** [comment]
Und wohin sollen die Daten dann gehen? 😊

**Comment by HerrSchleinig** [comment]
An ***@***.*** ***@***.***> :-)

**Comment by HerrBertling** [comment]
Ich vermute, GitHub hat nen eingebauten Selbstschutz, was das Posten von E-Mail-Adressen angeht? 😄 
![image](https://user-images.githubusercontent.com/1827373/116281245-cf95ef00-a789-11eb-9452-30d5ee027265.png)

**Comment by HerrSchleinig** [comment]
Wenn Du hier noch was brauchst, lass es mich gerne wissen ❤️

**Comment by HerrSchleinig** [comment]
Schau mal, was hältst Du von dem Fragebogen? https://docs.google.com/forms/d/e/1FAIpQLSeK9sZUQFxlI38RV6TqUxaHtOOHiv_EThP2LFG0Xz19asby6Q/viewform

**Comment by HerrSchleinig** [comment]
So, finales Feedbackformular: https://bit.ly/redezeitfeedback

**Comment by HerrSchleinig** [comment]
Ach, ich vergaß: Magst Du das Formular einmal als Link oben ins Menü stellen? Benannt mit "Feedback"?
