### ISSUE TITLE
Schlagwort-Filter auf AND statt OR

### ISSUE THREAD

**Issue by HerrBertling** [HerrBertling/virtualsupporttalks#9]
Vielleicht können wir im nächsten Jahr mal über den Ausbau der Filterung für besseres Matching nachdenken. Zum Bsp wenn jemand mehrere Filterpunkte festlegen will, um so einen noch genaueren Überblick über mögliche Coaches zu kriegen.

**Comment by HerrSchleinig** [comment]
Übrigens total gerne. Lass uns gerne die Filterung weiterentwickeln :-)

**Comment by HerrSchleinig** [comment]
Was auch gut passt:

- Gezielte Zuhörersuche nach Namen
- Männlich/Weiblich

**Comment by HerrSchleinig** [comment]
huhu, wie geht s dir? seid ihr wieder genesen? sag, meinst du, du kannst die and statt or geschichte implementieren? ❤️🙏🏻 hatten in den vergangenen tagen dazu ein paar anfragen. danke dir! 🌸
