### ISSUE TITLE
Mehrsprachige Buttons

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#94]
Hello,

das tut mir leid mit der Baustelle bei Euch und den Hassle den Ihr mit Euren Vermietern habt! Echt zum Kotzen! Wenn ich helfen kann, lass es mich umgehend wissen, ja?

Mir ist aufgefallen, dass die Button nur deutsch können bzw nur das können, was man als Text eingibt, jedoch nicht mehrsprachig :-)

LG, Flo

**Comment by HerrBertling** [comment]
Welche Buttons genau? 😅

**Comment by HerrSchleinig** [comment]
😄 Also alle grünen Buttons, die ich selbst bestücken kann. Nicht die aus der Navi oben. 

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________

**Comment by HerrSchleinig** [comment]
Danke Dir sehr! Das ist echt mega geworden ❤️❤️❤️

**Comment by HerrBertling** [comment]
öhm… @NoeliaEle did it :D
