### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by HerrSchleinig** [HerrBertling/virtualsupporttalks#95]
Hello!

Sorry noch mal ich...

Die englische FAQ wird beim ersten Klicken nicht angezeigt, erst wenn ich die Seite refreshe, siehe Bilder im Anhang. Ich hab schon nachgesehen, aber ich finde absolut keinen Fehler...

![Bildschirmfoto 2022-04-06 um 21 33 40](https://user-images.githubusercontent.com/80904689/162055469-04821a92-507f-4199-a92a-3e4ccd48f899.png)
![Bildschirmfoto 2022-04-06 um 21 33 27](https://user-images.githubusercontent.com/80904689/162055492-eb8f8ce0-3f91-4ec4-853c-126ad2568fd9.png)

**Comment by HerrSchleinig** [comment]
Die deutsche FAQ Seite ist fein. Keine Probleme.

**Comment by HerrBertling** [comment]
Könnte sein, dass der Link mit dem `/` enden muss. Ich hab das mal im CMS angepasst und schaue, ob es was bringt.

**Comment by HerrBertling** [comment]
And work it did. :tada:

**Comment by HerrSchleinig** [comment]
🥳🥳🥳❤️❤️❤️💪🏻💪🏻💪🏻 Wuhu!

Florian Schleinig
_____________

Flemingstraße 7
22299 Hamburg
e: ***@***.***
w: herrschleinig.de
m: +49177 46 18 912
_____________
