### ISSUE TITLE
Update coaches description to EN, RU and UK

### ISSUE THREAD

**Issue by NoeliaEle** [HerrBertling/virtualsupporttalks#98]

**Comment by HerrBertling** [comment]
Well, I should have passed the language into the Contentful query… 😬  fixed in https://github.com/HerrBertling/virtualsupporttalks/pull/78/commits/1dcb10a863184f3a9b7d98c1d98cf7bc130de420

**Comment by NoeliaEle** [comment]
Hi @HerrBertling , we have the functionality to display the coaches description in multiple languages but now we need to add it to contentful, right?

**Comment by HerrBertling** [comment]
Yes, if a coach doesn’t have one in the right language, it will fallback to german currently.
